language: shell
script:
- echo "test"
after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) &&
      [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "This will deploy!"
  else
    echo "This will not deploy!"
  fi
deploy:
  provider: script
  script: echo "deploying since tags"
  skip_cleanup: true
  on:
    tags: true
    branch: master
